name: Build Android

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, master ]

env:
  GH_PROXY_URL: ${{ secrets.GH_PROXY_URL }}
  GH_PROXY_SECRET: ${{ secrets.GH_PROXY_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Create google-services.json
        run: printf '%s' "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d -i > app/google-services.json

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
